// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoevccrhkkiopqimkuod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZXZjY3Joa2tpb3BxaW1rdW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNTQxNDUsImV4cCI6MjA1MjkzMDE0NX0.SjpKgqVLvwsp-CccAMoi2SCJR_Q4Mpb7YR1Sa7renbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);